apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: traffics
  namespace: traffics
  labels:
    app: traffics
spec:
  template:
    metadata:
      labels:
        app: traffics
    spec:
      containers:
      - name: traffics
        image: codeformuenster/traffic-dynamics-shiny:v0.3.5
        imagePullPolicy: IfNotPresent
        ports:
        - name: ui
          containerPort: 3838
