apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-apply
  namespace: kube-apply
  labels:
    app: kube-apply
data:
  Caddyfile: |
    :80
    gzip
    log stdout
    errors stdout
    root /var/www
    browse /var/www

    git {
      repo       https://github.com/codeformuenster/kubernetes-deployment.git
      path       repo
      # then       kubectl apply --dry-run --recursive --filename /var/www/repo/manifests
      then       /usr/local/bin/kubectl-apply
    }
